### ISSUE TITLE
Which desired distributions do you use in the paper?

### ISSUE THREAD

**Issue by isaacOnline** [oxai/debias-vision-lang#4]
You provide [code](https://github.com/oxai/debias-vision-lang/blob/master/debias_clip/measuring_bias.py) for measuring NDKL and MaxSkew where the desired distribution for the similar images is based on either demographic parity or equality of opportunity. When reporting results in your paper, which of these did you use? Apologies if this is somewhere I missed!

**Comment by Drummersbrother** [comment]
Hi! I think we used equality of opportunity for all results in the paper unless otherwise noted (i.e. uniform distribution)

**Comment by isaacOnline** [comment]
Thank you!
